### ISSUE TITLE
Lossが発散してしまう

### ISSUE THREAD

**Issue by Kanazawanaoaki** [Kanazawanaoaki/cook_eyes#3]
密集もしていない、しかもTrainとTestが一緒である簡単なデータセットを作成して学習をしてみたが、上手く行かずLossが発散してしまった。
![Screenshot from 2020-05-17 00-58-20](https://user-images.githubusercontent.com/38127823/82127084-0c244100-97ec-11ea-8e16-659a26c8925e.png)

**Comment by Kanazawanaoaki** [comment]
labels.txtにあとで画像を追加する予定だったトマトも含めていたのだが、データセットにトマトが存在しないためにrecallのようなものを計算する際などに０除算してlossが発散しているのでは無いかと考えた。  
しかし、labels.txtからtomatoを抜いた物を作ってみましたが、lossの発散は止まりませんでした。

**Comment by Kanazawanaoaki** [comment]
Tensorboardでの可視化をよくみると、
<img width="1138" alt="スクリーンショット 2020-05-17 13 34 23" src="https://user-images.githubusercontent.com/38127823/82146447-a97f8380-9885-11ea-830d-40140693b5da.png">
それぞれのGround Truthで一つづつラベルが出ていないのがわかる。  
これはhttps://github.com/k-okada/coral_usb_ros/blob/add_docker/docker/scripts/create_tf_record.py#L64-L66 に関連する？

**Comment by Kanazawanaoaki** [comment]
とりあえず、ダミーのポリゴンをつけてデータセットを作ることでやろうとしていた学習を行う事ができるようになった。
<img width="739" alt="スクリーンショット 2020-05-17 17 41 12" src="https://user-images.githubusercontent.com/38127823/82147117-8bffe900-9888-11ea-9ccb-17f915f15bbf.png">

**Comment by knorth55** [comment]
@Kanazawanaoaki 
これはどのデータセットでおきていますか？

**Comment by Kanazawanaoaki** [comment]
取り急ぎ、
https://github.com/Kanazawanaoaki/cook_eyes/issues/3#issuecomment-629791824  のラベルが出ていないデータセットは  
trainのみアノテーションしたデータ：https://github.com/Kanazawanaoaki/cook_eyes/tree/master/food_detector/food_only_data/four_veg_data  
確認用にtrainとtestを同じにしてあるVOC形式データセット：https://github.com/Kanazawanaoaki/cook_eyes/tree/master/food_detector/food_only_data/four_veg_data_tts_dataset  

https://github.com/Kanazawanaoaki/cook_eyes/issues/3#issuecomment-629792162 のダミーのアノテーションを入れてあるデータセットは、  
trainのみアノテーションしたデータ：https://github.com/Kanazawanaoaki/cook_eyes/tree/master/food_detector/food_only_data/try_dummy_later  
確認用にtrainとtestを同じにしてあるVOC形式データセット：https://github.com/Kanazawanaoaki/cook_eyes/tree/master/food_detector/food_only_data/try_dummy_later_dataset  

です。今googleドライブに上げているのでアップロードが終わり次第そちらをリンクで共有します。

**Comment by knorth55** [comment]
これって、この間のrotationの問題は解決されてますか？

**Comment by Kanazawanaoaki** [comment]
解決前のプログラムを使ってVOC変換をしたものですが、横向きで撮ったのでrotation問題はおきていなかったです。
![Screenshot from 2020-05-28 16-21-44](https://user-images.githubusercontent.com/38127823/83111716-fb36d200-a0ff-11ea-9882-7d5f39957f8a.png)

**Comment by knorth55** [comment]
なるほど、ありがとうございます。
元々はこのデータセットだと何も学習できてないってことですよね。
一応このcommitで治ったかな、いまチェック中なのでdlboxのdocker imageにはまだ変更が反映されていませんが、
https://github.com/knorth55/coral_usb_ros/commit/50cdc16b61ed9dc59b6c6116f35c75d9a82cb043

**Comment by knorth55** [comment]
![kanazawa_kitchen_dataset](https://user-images.githubusercontent.com/9300063/83113347-81ecae80-a102-11ea-8b47-106ff035381c.png)

**Comment by Kanazawanaoaki** [comment]
>元々はこのデータセットだと何も学習できてないってことですよね。
そうです。学習ができなくてhttps://github.com/Kanazawanaoaki/cook_eyes/issues/3#issuecomment-629791824 のようにでたらめなボックスが出るだけになっていました。  

ちゃんとラベル付けも出て学習もできるようになっていますね。ありがとうございます！

**Comment by knorth55** [comment]
dlbox1のdocker imageも更新したので時間があれば試してみてください。

**Comment by Kanazawanaoaki** [comment]
ありがとうございます。試してみて、うまく行きました！
<img width="1077" alt="スクリーンショット 2020-05-28 21 10 10" src="https://user-images.githubusercontent.com/38127823/83139616-a14a0280-a127-11ea-9f5e-398e3dfd2f4a.png">
